name: Build and Deploy to S3
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
 
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: website-files
        path: |
          index.html
          style.css
 
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from main branch
 
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: website-files
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://my-bucket-for-test11 --delete
 